name: tagpr
on:
  push:
    branches:
      - main

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.set-modules.outputs.modules }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Find tagpr modules
        id: set-modules
        run: |
          MODULES=$(find . -mindepth 2 -name ".tagpr" -exec dirname {} \; | sed 's|^\./||' | jq -R -s -c 'split("\n")[:-1]')
          echo "Found modules: ${MODULES}"
          echo "modules=${MODULES}" >> $GITHUB_OUTPUT

  tagpr:
    needs: setup-matrix
    if: ${{ needs.setup-matrix.outputs.modules != '[]' && needs.setup-matrix.outputs.modules != '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ${{ fromJson(needs.setup-matrix.outputs.modules) }}
      max-parallel: 1
    steps:
      - name: Create Github App token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          repositories: ${{ github.event.repository.name }}
          permission-contents: write
          permission-pull-requests: write
          permission-issues: read

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false
      
      - name: Run tagpr
        id: tagpr
        uses: Songmu/tagpr@b3fb89424646b06c8aa460f50307c60b6a541425 # v1.17.1
        with:
          config: ${{ matrix.module }}/.tagpr
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
